
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,2,upper('Recebido pela transportadora'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,3,upper('Geração de lista'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,4,upper('Em Rota'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,5,upper('A caminho do destinatário'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,6,upper('Entregue'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,7,upper('Reentregar'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,8,upper('Recebido no CD Reentregar'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,9,upper('Liberado'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,11,upper('Recebido no CD Ocorrência'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,12,upper('Agendado'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,13,upper('Calendarizado'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,14,upper('Em Transferência'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,15,upper('Transferido'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,16,upper('A Devolver Origem'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,17,upper('Recebido no CD A Devolver'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,18,upper('Devolução em Transferência'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,19,upper('Devolução Transferida'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,20,upper('Devolução em Rota'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,21,upper('Devolvido'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,22,upper('Pedido Cancelado'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,23,upper('Avaria Parcial - Armazém'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,24,upper('Avaria Parcial - Motorista'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,25,upper('Avaria Total - Armazém'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,26,upper('Avaria Total - Motorista'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,27,upper('Suspeita de extravio'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,28,upper('Extravio Total - Motorista'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,29,upper('Extravio Total - Armazém'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,30,upper('Sinistro Aguardando Seguradora'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,31,upper('Sinistro Solucionado'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,32,upper('Salvados'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,33,upper('Estornado'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,34,upper('CT-e autorizado'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,35,upper('Insucesso no Agendamento'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,36,upper('Análise de Perda'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,37,upper('Perda de Inventário'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,38,upper('Inventário Localizado'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,39,upper('Avaria aguardando análise de cobrança'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,40,upper('Coletado pela Transportadora'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,51,upper('Area de Risco > Solicito Novo Endereco de Entrega'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,52,upper('Atraso Operacional'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,53,upper('Carga Roubada'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,54,upper('Cliente indisponível solicitou agendamento'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,55,upper('Cliente mudou de endereço'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,56,upper('Destinatario Alega Mercadoria Desac com Pedido'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,57,upper('Destinatario Ausente'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,58,upper('Destinatário Ausente 1a Tentativa'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,59,upper('Destinatário Ausente 2a Tentativa'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,60,upper('Destinatário Ausente 3a Tentativa'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,61,upper('Destinatario Desconhecido'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,62,upper('Destinatario Retira'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,63,upper('Devolução Autorizada pelo Remetente'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,64,upper('Dificuldades na região de entrega'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,65,upper('Embalagem Avariada'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,66,upper('Endereco Dest Não Localizado'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,67,upper('Entrega não efetuada - feriado local'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,68,upper('Entrega Prejudicada Pelo Horario/Transito'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,69,upper('Excesso de chuva'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,70,upper('Falta de Mercadoria'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,71,upper('Falta no recebimento de transferência'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,72,upper('Mercadoria Avariada'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,73,upper('Mercadoria Retida Pela Fiscalização'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,74,upper('Não Visitado'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,75,upper('Pedido Em Analise de Extravio'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,76,upper('Produto não entra na residencia'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,77,upper('Produto recusado na devolução pelo embarcador'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,78,upper('Recusa por pedido cancelado'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,79,upper('Recusado'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,80,upper('Recusado Pelo Cliente Por Motivos Pessoais'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,81,upper('Greve / Manifestação / Paralisação'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,82,upper('Cep não atendido pela base'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,83,upper('Quebra de Veículo'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,84,upper('Número não localizado'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,85,upper('Aguardando posicionamento Embarcador'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,86,upper('Local fechado'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (1,87,upper('Sem registro de entrada na transportadora'));


INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,2,upper('Aguardando Agendamento'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,3,upper('Recebido pela transportadora'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,4,upper('CT-e autorizado'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,5,upper('Geração de lista'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,6,upper('Geração de lista de subcontrato'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,7,upper('Em Rota'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,8,upper('A caminho da Loja'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,9,upper('Entregue na Loja'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,10,upper('Liberado'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,11,upper('Agendado'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,12,upper('Insucesso no Agendamento'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,13,upper('Calendarizado'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,14,upper('Reentregar'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,15,upper('Suspeita de extravio'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,16,upper('Extravio'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,17,upper('Pedido Cancelado'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,18,upper('Avaria Parcial'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,19,upper('Avaria Total'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,20,upper('Recebido no CD'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,21,upper('Recebido no CD Ocorrência'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,22,upper('Recebido no CD Reentregar'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,23,upper('Recebido no CD A Devolver'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,24,upper('Devolução Em Transferência'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,25,upper('Devolução Transferida'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,27,upper('Em transferência'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,28,upper('Transferido'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,29,upper('A devolver origem'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,30,upper('Devolução em Rota'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,31,upper('Devolvido'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,32,upper('Estornado'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,50,upper('Dados insuficientes para entrega'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,51,upper('Dificuldades na região de entrega'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,52,upper('Endereço não localizado'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,53,upper('Entrega não efetuada - feriado local'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,54,upper('Excesso de chuva'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,55,upper('Loja Fechada'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,56,upper('Mercadoria em desacordo com o pedido'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,57,upper('Praça não atendida'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,58,upper('Problemas com fiscalização'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,59,upper('Problemas no transporte de devolução Insucesso'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,60,upper('Produto em desacordo com o manifesto'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,61,upper('Greve / Manifestação / Paralisação'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,62,upper('Quebra de Veículo'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,63,upper('Carga Roubada'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,64,upper('Cliente indisponível solicitou agendamento'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,65,upper('Entrega prejudicada pelo horário'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (2,66,upper('Aguardando Retirada'));

INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,2,upper('Solicitação recebida pela transportadora'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,3,upper('Agendado'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,4,upper('Coleta Impressa'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,5,upper('Coleta Em Trânsito'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,6,upper('A caminho do destinatário'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,7,upper('Coletado'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,8,upper('Recebido no CD Coletado'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,9,upper('Recoletar'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,10,upper('Em Transferência'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,11,upper('Transferido'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,12,upper('A Devolver Destino'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,13,upper('Devolução em Rota'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,14,upper('Devolvido'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,15,upper('Calendarizado'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,16,upper('Ocorrência'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,17,upper('Coleta Cancelada'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,18,upper('Coleta Recusada pela Operação - Divergência'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,19,upper('Coleta Devolvida ao Consumidor'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,20,upper('Coleta Finalizada - Erro Motorista'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,21,upper('Coleta Finalizada - Erro Base'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,22,upper('Sinistro Aguardando Seguradora'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,23,upper('Sinistro Solucionado'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,24,upper('Avaria Parcial - Armazém'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,25,upper('Avaria Parcial - Motorista'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,26,upper('Avaria Total - Armazém'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,27,upper('Avaria Total - Motorista'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,28,upper('Suspeita de extravio'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,29,upper('Extravio Total - Armazém'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,30,upper('Extravio Total - Motorista'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,31,upper('Salvados'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,33,upper('Estorno'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,51,upper('Aguardando posicionamento Embarcador'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,52,upper('Area de Risco'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,53,upper('Avaria no Transporte'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,54,upper('Baú cheio'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,55,upper('Cliente ausente'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,56,upper('Cliente Ausente 1a Tentativa'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,57,upper('Cliente Ausente 2a Tentativa'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,58,upper('Cliente Ausente 3a Tentativa'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,59,upper('Cliente descartou/doou o produto'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,60,upper('Cliente indisponível solicitou agendamento'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,61,upper('Cliente mudou de endereço'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,62,upper('Coleta Cancelada - Cliente desistiu'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,63,upper('Coleta cancelada pelo SAC'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,64,upper('Coleta não realizada por item divergente'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,65,upper('Coleta não realizada produto desembalado'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,66,upper('Coleta prejudicada pelo horário'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,67,upper('Coleta Recusada - aguarda estorno ou entrega de novo item'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,68,upper('Coleta Recusada - Cliente não reconhece a coleta'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,69,upper('Coleta Recusada - cliente se recusa a devolver'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,70,upper('Coleta recusada pelo cliente, aguarda troca casada'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,71,upper('Coletado por Outra Transportadora'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,72,upper('Condomínio com restrição de horário'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,73,upper('Divergência na Quantidade de Volumes'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,74,upper('Endereço não localizado'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,75,upper('Falta no recebimento de transferência'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,76,upper('Feriado nacional'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,77,upper('Local Fechado'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,78,upper('Loja fechada'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,79,upper('Loja recusou processo de coleta'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,80,upper('Material não Disponivel'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,81,upper('Material não Localizado'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,82,upper('Não Visitado'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,83,upper('Praça de coleta não atendida pelo transportador'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,84,upper('Problemas com a fiscalização'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,85,upper('Problemas de endereço de coleta'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,86,upper('Produto em outro endereço'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,87,upper('Produto Montado/Desembalado'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,88,upper('Produto recusado na devolução pelo embarcador'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,89,upper('Roubo do item coletado'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,90,upper('Venda Cancelada'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (3,91,upper('Greve / Manifestação / Paralisação'));


INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (4,1,upper('Arquivo Recebido pela Transportadora'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (4,2,upper('Inicio de Carregamento'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (4,3,upper('Termino de Carregamento'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (4,4,upper('Inicio de Viagem'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (4,5,upper('Chegada no Destino'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (4,6,upper('Inicio de Descarregamento'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (4,7,upper('Termino de Descarregamento'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (4,8,upper('Termino de Viagem'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (4,51,upper('Divergências com a nota fiscal (produto, preço, quantidade)'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (4,50,upper('Endereço não localizado'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (4,54,upper('Local fechado'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (4,52,upper('Sinistro roubo'));
INSERT INTO scr_ocorrencias_track3r(categoria, id_ocorrencia, ocorrencia) VALUES (4,53,upper('Sinistro acidente'));


