INSERT INTO edi_ocorrencias_comprovei (codigo_status, status) VALUES (1002,'EMBALAGEM AVARIADA');
INSERT INTO edi_ocorrencias_comprovei (codigo_status, status) VALUES (15,'ATRASO NA ENTREGA');
INSERT INTO edi_ocorrencias_comprovei (codigo_status, status) VALUES (18,'FORA DO AGENDAMENTO');
INSERT INTO edi_ocorrencias_comprovei (codigo_status, status) VALUES (20,'PROBLEMA COM O PEDIDO');
INSERT INTO edi_ocorrencias_comprovei (codigo_status, status) VALUES (998,'MOTORISTA NAO JUSTIFICOU');
INSERT INTO edi_ocorrencias_comprovei (codigo_status, status) VALUES (1001,'ITEM AVARIADO');
INSERT INTO edi_ocorrencias_comprovei (codigo_status, status) VALUES (17,'FERIADO LOCA/NACIONAL');
INSERT INTO edi_ocorrencias_comprovei (codigo_status, status) VALUES (12,'FORA DO HORARIO');
INSERT INTO edi_ocorrencias_comprovei (codigo_status, status) VALUES (13,'ESTABELECIMENTO FECHADO');
INSERT INTO edi_ocorrencias_comprovei (codigo_status, status) VALUES (1,'ENTREGA COM RESTRICOES');
INSERT INTO edi_ocorrencias_comprovei (codigo_status, status) VALUES (102,'COLETA DIVERGENTE');
INSERT INTO edi_ocorrencias_comprovei (codigo_status, status) VALUES (14,'FALTA DE XML');
INSERT INTO edi_ocorrencias_comprovei (codigo_status, status) VALUES (16,'EXCESSO DE CARGA');
INSERT INTO edi_ocorrencias_comprovei (codigo_status, status) VALUES (19,'PROBLEMA COM MERCADORIA');
INSERT INTO edi_ocorrencias_comprovei (codigo_status, status) VALUES (21,'SISTEMA DO CLIENTE FORA DO AR');
INSERT INTO edi_ocorrencias_comprovei (codigo_status, status) VALUES (22,'PROBLEMA RECEBIMENTO CLIENTE');
INSERT INTO edi_ocorrencias_comprovei (codigo_status, status) VALUES (101,'COLETA EFETUADA');
INSERT INTO edi_ocorrencias_comprovei (codigo_status, status) VALUES (200,'PARADA PARA ALMOCO');
INSERT INTO edi_ocorrencias_comprovei (codigo_status, status) VALUES (201,'ACIDENTE');
INSERT INTO edi_ocorrencias_comprovei (codigo_status, status) VALUES (202,'PROBLEMA NO VEICULO');
INSERT INTO edi_ocorrencias_comprovei (codigo_status, status) VALUES (995,'ROTA CANCELADA');
INSERT INTO edi_ocorrencias_comprovei (codigo_status, status) VALUES (11,'EXCESSO DE VEICULOS');
INSERT INTO edi_ocorrencias_comprovei (codigo_status, status) VALUES (203,'TRANSITO PARADO');
INSERT INTO edi_ocorrencias_comprovei (codigo_status, status) VALUES (300,'NAO LIBERADO PELO CLIENTE');
INSERT INTO edi_ocorrencias_comprovei (codigo_status, status) VALUES (301,'NAO EFETUADA');
INSERT INTO edi_ocorrencias_comprovei (codigo_status, status) VALUES (302,'NAO HA ITENS PARA COLETAR');
INSERT INTO edi_ocorrencias_comprovei (codigo_status, status) VALUES (1003,'ESPECIFICACAO ERRADA');
INSERT INTO edi_ocorrencias_comprovei (codigo_status, status) VALUES (0,'ENTREGA REALIZADA NORMALMENTE');
INSERT INTO edi_ocorrencias_comprovei (codigo_status, status) VALUES (1004,'DEVOLUCAO');

